### ISSUE TITLE
好奇这个文件存储在哪里了

### ISSUE THREAD

**Issue by qiuwenbo1** [hughfenghen/opfs-tools-explorer#1]
![image](https://github.com/hughfenghen/opfs-tools-explorer/assets/51011716/57a833a8-7632-4de2-bfa6-9cf87bbe5662)
不懂ts，好奇这个文件存储在哪里了呢？可以在本地路径找到吗

**Comment by hughfenghen** [comment]
由浏览器管理，按Web站点（源）隔离，对用户不可见
